// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDElaFmgIoYdwHF0U5dOgjqGBqYkNSNC3w',
    appId: '1:578617644365:web:1474ea7bd0ef76cec85304',
    messagingSenderId: '578617644365',
    projectId: 'togoavis-7e2c1',
    authDomain: 'togoavis-7e2c1.firebaseapp.com',
    storageBucket: 'togoavis-7e2c1.firebasestorage.app',
    measurementId: 'G-DVK494FPS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdTRZW5hVnZnxB61DxFHdzvcFYi-Hyrqk',
    appId: '1:578617644365:android:f98d34944fb28bdfc85304',
    messagingSenderId: '578617644365',
    projectId: 'togoavis-7e2c1',
    storageBucket: 'togoavis-7e2c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBotfaiVgNKsATIsoEFlMPKWclhHLQAANo',
    appId: '1:578617644365:ios:858825f17b61108ac85304',
    messagingSenderId: '578617644365',
    projectId: 'togoavis-7e2c1',
    storageBucket: 'togoavis-7e2c1.firebasestorage.app',
    iosBundleId: 'com.example.pst',
  );
}
